batch_size: 32
discount: 0.99
initial_eps: 1
end_eps: 0.1
eps_decay_period: 1000
eval_eps: 0
eval_freq: 100.0
buffer_size: 100
optimizer: Adam
optimizer_parameters:
  #amsgrad: true
  lr: 0.001
# Different from Tianshou
polyak_target_update: true
random_buffer: false
target_update_freq: 100
tau: 0.005
#train_freq: 1
# I need to differentiate between online and offline buffer size
replay_buffer_size: 20000

# *** Environment ***
n_past_obs: 1
actions: [-1, 0, 1] #[-1, -0.5, 0, 0.5, 1]
max_episode_steps: 5000
action_type: "discrete"
include_action: true
include_deltas: true
mult_pos_theta: false
mult_deltas: false
scaling: true

# *** VQC parameter ***
# Number of data re-uploading layers
data_reuploading_layers: 	1
# Type of data re-uploading ("normal", "cyclic")
data_reuploading_type: 	"normal"
# Gradient estimation method ("SPSA, "Parameter-shift")
grad_type:			"SPSA"
# SPSA epsilon (perturbation scaling)
epsilon:			0.1
# Type of executor ("analytical", "shot-based", "ibmq")
quantum_compute_method:	"analytical"
# Type of weight initialization ("random, "ones", "zeros")
quantum_weight_initialization: "random"
# Number of outputs from VQC
output_dim:			3
# Number of inputs to the VQC
input_dim:			10
# Add a fully connected layer to the input.
add_input_weights:		False
# Add a fully connected layer to the output.
add_output_weights:		False
# Add a scaling parameter to the inputs.
input_scaling:			False
# Add a scaling parameter to the outputs.
output_scaling:		True
# Type of input weight initialization. ("random, "ones")
input_weight_initialization:	"random"
# Type of output weight initialization. ("random, "ones")
output_weight_initialization:	"ones"
# Ignored for now
post_process_decode:		"None"
# Number of parallel process generated
num_parallel_process:		6
# Number of shots to be used for shot-based simulator.
shots:				512
# Maximum time for ibmq session in seconds
ibmq_session_max_time:		7*60*60
